# .github/workflows/ci.yml
name: Frontend CI (root)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: fe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sanity check
        run: |
          pwd
          ls -la
          node -v
          npm -v

      - name: Install deps
        run: npm i

      - name: Build (skip if script missing)
        env:
          # якщо vite читає це під час build — підстав свою URL або secrets
          VITE_API_URL: http://localhost:5174
        run: npm run -s build --if-present
