name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # ВАЖЛИВО: всі run-команди виконуються в client/
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install deps
        run: npm ci

      # опц.: якщо нема скрипта — крок просто пропуститься
      - name: Lint
        run: |
          if npm run -s lint >/dev/null 2>&1; then
            npm run lint
          else
            echo "No lint script — skipping."
          fi

      # опц.: Vitest/Jest
      - name: Test
        run: |
          if npm run -s test -- --run >/dev/null 2>&1; then
            npm test -- --run
          else
            echo "No test script — skipping."
          fi

      # Якщо у вас у білді потрібна змінна Vite — задайте тут
      - name: Build
        env:
          VITE_API_URL: http://localhost:5174
        run: npm run build
